from src.core.game import Game

def main():
    game = Game()
    game.run()

if __name__ == "__main__":
    main()


    #SIGUE DOCUMENTANDO FLOJOOOOOOO

    #PODRIAS METERLE UNA ANIMACIONCITA A LA TWIDDLE

    #TRATA DE ORGANIZAR LAS COSAS Y DOCUMENTAR EN EL PLAY_STATE, DE RESTO ME PARECE QUE VAS BIEN

    #REVISA LO QUE VA CAMBIANDO DIEGO Y COMPAGINEN BIEN LOS CAMBIOS Y LAS FISICAS
    
    #REVISA SI VAS A DIBUJAR LA MESA CON LA FUNCION DE RENDERIZADO ESA CUANDO LA ARREGLES
    #  O VAS A DIBUJAR UN SPRITE DE CERO (ARREGLA LA FUNCION, LO PUEDES HACER CON .DRAW CREO, Y TU WORLD TO SCREEN)