from src.core.game import Game

def main():
    game = Game()
    game.run()

if __name__ == "__main__":
    main()


    #SIGUE DOCUMENTANDO FLOJOOOOOOO

    #PODRIAS METERLE UNA ANIMACIONCITA AL TWIDDLE

    #REVISA LO QUE VA CAMBIANDO DIEGO Y COMPAGINEN BIEN LOS CAMBIOS Y LAS FISICAS

    #RECUERDA REVISAR LOS CACHES EN LOS CASOS DE POLIGONOS XY, SEAN ESTATICOS O DINAMICOS

    #AGREGA IMPLEMENTACIONES A ENTER Y EXIT EN LOS STATES(PARA QUE GUARDEN Y BORREN CACHE)