from src.core.game import Game

def main():
    game = Game()
    game.run()

if __name__ == "__main__":
    main()


    #SIGUE DOCUMENTANDO FLOJOOOOOOO

    #LA RAQUETA TIENE QUE TENER SU ALTURA CON RESPECTO A EL INICIO DEL MANGO
    #  (AHORA ESTA MEJOR PERO TIENE UN POQUITO DE OFFSET POR EL ALPHA)
    
    #REVISA SI VAS A DIBUJAR LA MESA CON LA FUNCION DE RENDERIZADO ESA CUANDO LA ARREGLES
    #  O VAS A DIBUJAR UN SPRITE DE CERO (ARREGLA LA FUNCION, LO PUEDES HACER CON >DRAW CREO, Y TU WORLD TO SCREEN)